[GENERAL]
PORT = 3001
SIMILARITY_MEASURE = "cosine"
KEEP_ALIVE = "5m"

[MODELS.OPENAI]
API_KEY = "${OPENAI_API_KEY}"

[MODELS.GROQ]
API_KEY = "${GROQ_API_KEY}"

[MODELS.ANTHROPIC]
API_KEY = "${ANTHROPIC_API_KEY}"

[MODELS.GEMINI]
API_KEY = "${GEMINI_API_KEY}"

[MODELS.CUSTOM_OPENAI]
API_KEY = "${CUSTOM_OPENAI_API_KEY}"
API_URL = "${CUSTOM_OPENAI_API_URL}"

[MODELS.OLLAMA]
API_URL = "${OLLAMA_API_URL}"

[API_ENDPOINTS]
SEARXNG = "${SEARXNG_API_URL}" 