version: '3.8'

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: perplexica-searxng
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - INSTANCE_NAME=perplexica-searxng
    networks:
      - perplexica-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: ${REGISTRY_IMAGE_BACKEND:-perplexica-backend}:${IMAGE_TAG:-latest}
    container_name: perplexica-backend
    environment:
      - NODE_ENV=production
      - SEARXNG_API_URL=http://searxng:8080
      - PORT=3001
      # Add your model API keys here or use Coolify secrets
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OLLAMA_API_URL=${OLLAMA_API_URL}
    volumes:
      - backend-data:/home/perplexica/data
      - uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml:ro
    depends_on:
      searxng:
        condition: service_healthy
    networks:
      - perplexica-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:3001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=/api
        - NEXT_PUBLIC_WS_URL=ws://backend:3001
    image: ${REGISTRY_IMAGE_FRONTEND:-perplexica-frontend}:${IMAGE_TAG:-latest}
    container_name: perplexica-frontend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_WS_URL=ws://backend:3001
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:
    driver: bridge

volumes:
  backend-data:
    driver: local
  uploads:
    driver: local 