version: '3.8'

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: perplexica-searxng
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - INSTANCE_NAME=perplexica-searxng
    networks:
      - perplexica-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: ${REGISTRY_IMAGE_BACKEND:-perplexica-backend}:${IMAGE_TAG:-latest}
    container_name: perplexica-backend
    environment:
      - NODE_ENV=production
      - SEARXNG_API_URL=https://search.nj1.cakez.net/
      - PORT=3001
      # API Keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OLLAMA_API_URL=${OLLAMA_API_URL}
    ports:
      - "12001:3001"
    volumes:
      - backend-data:/home/perplexica/data
      - uploads:/home/perplexica/uploads
    depends_on:
      - searxng
    networks:
      - perplexica-network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=https://pplx-backend.nj1.cakez.net/api
        - NEXT_PUBLIC_WS_URL=wss://pplx-backend.nj1.cakez.net
    image: ${REGISTRY_IMAGE_FRONTEND:-perplexica-frontend}:${IMAGE_TAG:-latest}
    container_name: perplexica-frontend
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NEXT_PUBLIC_API_URL=http://backend:3001
      - NEXT_PUBLIC_WS_URL=ws://backend:3001
    ports:
      - "12000:3000"
    depends_on:
      - backend
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:
    driver: bridge

volumes:
  backend-data:
    driver: local
  uploads:
    driver: local 
