[build]
builder = "DOCKERFILE"
dockerfilePath = "frontend.dockerfile"

[deploy]
startCommand = "node .next/standalone/server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
numReplicas = 1 