[build]
builder = "DOCKERFILE"
dockerfilePath = "backend.dockerfile"

[deploy]
startCommand = "yarn start"
healthcheckPath = "/api"
healthcheckTimeout = "180"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 