[build]
builder = "DOCKERFILE"
dockerfilePath = "backend.dockerfile"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3 